const INTERNAL_SERVER_ERROR = 500
const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const NOT_FOUND = 404
const OK = 200
const CREATED = 201
const NO_CONTENT = 204

module.exports = {
  INTERNAL_SERVER_ERROR,
  BAD_REQUEST,
  UNAUTHORIZED,
  NOT_FOUND,
  OK,
  CREATED,
  NO_CONTENT,
}
